apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base

nameSuffix: "-mongo-aws"

patchesStrategicMerge:
  - placement-rule.yaml
  - subscription.yaml
  - git-channel.yaml
