apiVersion: "app.k8s.io/v1beta1"
kind: "Application"
metadata:
   name: "airline-application"
spec:
   componentKinds:
      - group: "apps.open-cluster-management.io"
        kind: "Subscription"
   descriptor: {}
   selector:
      matchExpressions:
         - key: "cloud"
           operator: "In"
           values:
              - "Amazon"
              - "Azure"
              - "Google"
