apiVersion: "apps.open-cluster-management.io/v1"
kind: "PlacementRule"
metadata:
  name: "airline-component"
spec:
  clusterConditions:
    - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: "dev"
      clustertag: "airline"
