apiVersion: "apps.open-cluster-management.io/v1"
kind: "Subscription"
metadata:
  name: "hybrid-airline-subscription"
  labels:
    cloud: all
  annotations:
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: "airline-hybrid-demo/some-channel-name-to-be-replaced"
  placement:
    placementRef:
      kind: "PlacementRule"
      name: "some-placement-rule-name-to-be-replaced"
